<a href="https://colab.research.google.com/github/demirbey05/pytorch-cookbook/blob/main/Torch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
# Create array of range 1 to 12
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.numel()

12

In [5]:
x.shape

torch.Size([12])

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [7]:
X.shape

torch.Size([3, 4])

In [8]:
Y = x.reshape(3,-1)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [9]:
#Create 2 3x4 zeros Matrix meaning (2,3,4) shape

torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
#Create 2 3x4 ones Matrix meaning (2,3,4) shape
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
#Create 2 3x4 random Matrix meaning (2,3,4) shape  Drawn from Gaussina mean 0 stdev 1

torch.randn((2,3,4))


tensor([[[ 0.2971,  0.1515, -0.1793,  1.2265],
         [ 0.8684, -0.9146, -0.9149, -2.1415],
         [-0.5241, -1.2236, -0.8621, -0.3396]],

        [[ 0.7516,  0.4142, -0.3551,  1.3370],
         [ 0.1289,  1.0716, -0.3474,  0.7153],
         [ 0.8390,  0.6577, -0.7993,  0.7912]]])

In [12]:
#Create torch tensor manually with shape of 2,3,4
a = torch.tensor([[[2,1,3,4],[2,4,5,6],[6,5,3,2]],[[1,2,3,4],[2,3,4,5],[5,6,7,8]]])
a.shape

torch.Size([2, 3, 4])

# Indexing & Slicing

In [13]:
# Indexing start with zero , X[start:stop] --> [start,stop) , -1 starts from the end
# When only one index is indicated in kth order tensor, the axis 0 will be selected
a[-1] # returns last matrix
a[0:2] # returns all
a[0:-1] # returns first matrix

tensor([[[2, 1, 3, 4],
         [2, 4, 5, 6],
         [6, 5, 3, 2]]])

In [14]:
# We can index in more detail by indicating more index
a[0,0,0] = 3 # first matrix, first row , first column(axis 0,1,2)
a

tensor([[[3, 1, 3, 4],
         [2, 4, 5, 6],
         [6, 5, 3, 2]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5],
         [5, 6, 7, 8]]])

In [15]:
# To assign multiple elements
a[:1,:] = 12 ## assign first matrix's elems to 12
a

tensor([[[12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12]],

        [[ 1,  2,  3,  4],
         [ 2,  3,  4,  5],
         [ 5,  6,  7,  8]]])

# Operations

In [16]:
# Get exp(x) elementwise
torch.exp(a)

tensor([[[1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
         [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
         [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05]],

        [[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02],
         [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03]]])

In [17]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([5,6,7,8],dtype=torch.float32)

x+y , x-y , x*y, x/y , x**y

(tensor([ 6.,  8., 10., 12.]),
 tensor([-4., -4., -4., -4.]),
 tensor([ 5., 12., 21., 32.]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]),
 tensor([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]))

In [18]:
# Concatenate two tensors
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]],dtype=torch.float32)
torch.cat((X,Y),dim=0) , torch.cat((X,Y),dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [19]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [20]:
X.sum()

tensor(66.)

# Broadcasting

In [21]:
# In different shapes, the operation is executed by broadcasting

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [22]:
# broadcast produces 3x2 tensor
a + b
"""
a is converted to 0 0
                  1 1
                  2 2

b is converted to 0 1
                  0 1
                  0 1

"""

'\na is converted to 0 0\n                  1 1\n                  2 2\n\nb is converted to 0 1\n                  0 1\n                  0 1\n\n'

In [23]:
x=torch.randn(60).reshape((5,4,3))
y=torch.ones((1,4,3))
x,y

(tensor([[[-0.7479, -0.2046, -0.1488],
          [ 0.8685, -0.5005,  0.8580],
          [ 1.1321,  0.1802,  0.1358],
          [ 1.8522, -2.2141,  0.0670]],
 
         [[ 0.2948, -2.4121,  0.0735],
          [ 1.3294, -1.1234,  1.6653],
          [-0.6512, -0.7591,  1.1660],
          [-0.7306,  0.8818,  0.2583]],
 
         [[-0.0519,  0.2878,  0.9468],
          [-1.4844,  1.7712, -0.6595],
          [-1.2198,  1.0014, -0.0080],
          [ 0.2721,  0.0577, -0.4901]],
 
         [[ 0.0973,  0.8331,  0.6497],
          [-0.0385,  0.2135, -0.6522],
          [ 1.6963,  0.5242,  0.3073],
          [ 0.9245, -0.1064,  0.5449]],
 
         [[-0.1452, -0.1374,  1.5901],
          [ 0.4429,  0.2623,  0.2839],
          [-0.3637, -0.1294,  0.5234],
          [ 0.7920, -1.3822, -1.2893]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [24]:
Y = torch.zeros((3,4))
X = torch.ones((3,4))

print(id(X))
print(id(Y))

Y = Y + X
id(Y)
#The id will change,that means python reallocated new object

139715309046656
139715309045856


139715309044496

In [25]:
Y = torch.ones((3,4))
X = torch.ones((3,4))
print(id(X))
print(id(Y))

Y[:] = X+ Y
id(Y)
#Id wont change, so more effective usage of the memory

139715309048176
139715309047936


139715309047936

# Data Preprocessing

In [26]:
import os


os.makedirs(os.path.join("..","data"),exist_ok = True)
data_path = os.path.join("..","data","house_tiny.csv")

with open(data_path,'w') as f:
  f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')


In [27]:
import pandas as pd

data = pd.read_csv("../data/house_tiny.csv")
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [28]:
inputs,targets = data.iloc[:,:2],data.iloc[:,2]
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1

In [29]:
#To impute nan in non-categorical variables is to take mean of the column
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1

In [30]:
#To load to torch tensor
X= torch.tensor(inputs.to_numpy(dtype=float))
y= torch.tensor(targets.to_numpy(dtype=float))
X,y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))

# Linear Algebra

In [31]:
# Scalars are 1D tensors
x = torch.tensor(5)
y = torch.tensor(6)

x+y,x*y,x-y

(tensor(11), tensor(30), tensor(-1))

In [32]:
A = torch.arange(30,dtype=torch.float32).reshape(2,5,3)
A.sum(axis=0), A, A.mean(axis=0),A.sum(axis=0)/A.shape[0],A

(tensor([[15., 17., 19.],
         [21., 23., 25.],
         [27., 29., 31.],
         [33., 35., 37.],
         [39., 41., 43.]]),
 tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.],
          [12., 13., 14.]],
 
         [[15., 16., 17.],
          [18., 19., 20.],
          [21., 22., 23.],
          [24., 25., 26.],
          [27., 28., 29.]]]),
 tensor([[ 7.5000,  8.5000,  9.5000],
         [10.5000, 11.5000, 12.5000],
         [13.5000, 14.5000, 15.5000],
         [16.5000, 17.5000, 18.5000],
         [19.5000, 20.5000, 21.5000]]),
 tensor([[ 7.5000,  8.5000,  9.5000],
         [10.5000, 11.5000, 12.5000],
         [13.5000, 14.5000, 15.5000],
         [16.5000, 17.5000, 18.5000],
         [19.5000, 20.5000, 21.5000]]),
 tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.],
          [12., 13., 14.]],
 
         [[15., 16., 17.],
          [18., 19., 20.],
          [21., 

In [33]:
B = torch.arange(6, dtype=torch.float32).reshape(2, 3)
B.sum(axis=1),B.sum(axis=1,keepdims=True),B.sum(axis=0,keepdims=True),B

(tensor([ 3., 12.]),
 tensor([[ 3.],
         [12.]]),
 tensor([[3., 5., 7.]]),
 tensor([[0., 1., 2.],
         [3., 4., 5.]]))

In [34]:
A.sum(axis=0).shape,A.sum(axis=0,keepdims=True).shape
#keepdims=True makes output axis = i to 1

(torch.Size([5, 3]), torch.Size([1, 5, 3]))

## Dot Products

In [35]:
x = torch.ones(3)
y = x.clone()
torch.dot(x,y),torch.sum(x*y),x.reshape(3,1)

(tensor(3.),
 tensor(3.),
 tensor([[1.],
         [1.],
         [1.]]))

# Automatic Differentiation

In [36]:
x = torch.arange(4,dtype=torch.float32)
x.requires_grad_(True)
x,x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), None)

In [37]:
y = 2*torch.dot(x,x) ## calculate 2*xTx


In [38]:
y.backward()
x.grad #the derivative is 4*x

tensor([ 0.,  4.,  8., 12.])

In [39]:
# Note that PyTorch does not automatically reset the gradient buffer when we record a new gradient. Instead, the new gradient is added to the already-stored gradient
x.grad.zero_()  # Reset the gradient
y = x.sum()
y.backward()

In [40]:
x.grad

tensor([1., 1., 1., 1.])

For vector-valued function, we cannot get the Jacobian directly. Instead pytorch returns vector-Jacobian product. vᵀ・J, to pass v, we will use gradient parameter

In [41]:
x.grad.zero_()
y = x * x
y.backward(gradient = torch.ones((len(y))))
x.grad

tensor([0., 2., 4., 6.])

In [42]:
# Standard gradient 3*x^2
x.grad.zero_()
y = x * x
z = y * x
z.sum().backward()

In [43]:
x.grad

tensor([ 0.,  3., 12., 27.])

In [44]:
# Detaching will yield u instead of 3x^2
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()

In [45]:
x.grad

tensor([0., 1., 4., 9.])

## Mixing Autograd w/ Python Flow

In [46]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

In [47]:
a = torch.randn(size=(),requires_grad=True)
d = f(a)
d.backward()

In [48]:
a.grad == d / a


tensor(True)

4 Steps :
(i) attach gradients to those variables with respect to which we desire derivatives;
(ii) record the computation of the target value;
(iii) execute the backpropagation function;
(iv) access the resulting gradient.

In [52]:
x = torch.arange(4,dtype=torch.float32,requires_grad=True)
y = torch.sin(x)
y.backward(gradient = torch.ones(len(y)))
x.grad

tensor([ 1.0000,  0.5403, -0.4161, -0.9900])