<a href="https://colab.research.google.com/github/demirbey05/pytorch-cookbook/blob/main/Torch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import torch

In [19]:
# Create array of range 1 to 12
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [20]:
x.numel()

12

In [21]:
x.shape

torch.Size([12])

In [22]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X.shape

torch.Size([3, 4])

In [24]:
Y = x.reshape(3,-1)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [25]:
#Create 2 3x4 zeros Matrix meaning (2,3,4) shape

torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [26]:
#Create 2 3x4 ones Matrix meaning (2,3,4) shape
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [27]:
#Create 2 3x4 random Matrix meaning (2,3,4) shape  Drawn from Gaussina mean 0 stdev 1

torch.randn((2,3,4))


tensor([[[ 2.0623,  0.9287,  0.7471,  0.5415],
         [ 1.8868,  0.6603, -2.2540, -1.1877],
         [ 0.8624, -0.9963, -1.4766, -0.3380]],

        [[-0.2788,  0.6310,  0.5811, -1.0070],
         [-0.1734,  1.1398,  0.0444,  1.3013],
         [-0.8593,  1.0586,  0.8269,  0.9366]]])

In [28]:
#Create torch tensor manually with shape of 2,3,4
a = torch.tensor([[[2,1,3,4],[2,4,5,6],[6,5,3,2]],[[1,2,3,4],[2,3,4,5],[5,6,7,8]]])
a.shape

torch.Size([2, 3, 4])

# Indexing & Slicing

In [29]:
# Indexing start with zero , X[start:stop] --> [start,stop) , -1 starts from the end
# When only one index is indicated in kth order tensor, the axis 0 will be selected
a[-1] # returns last matrix
a[0:2] # returns all
a[0:-1] # returns first matrix

tensor([[[2, 1, 3, 4],
         [2, 4, 5, 6],
         [6, 5, 3, 2]]])

In [30]:
# We can index in more detail by indicating more index
a[0,0,0] = 3 # first matrix, first row , first column(axis 0,1,2)
a

tensor([[[3, 1, 3, 4],
         [2, 4, 5, 6],
         [6, 5, 3, 2]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5],
         [5, 6, 7, 8]]])

In [31]:
# To assign multiple elements
a[:1,:] = 12 ## assign first matrix's elems to 12
a

tensor([[[12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12]],

        [[ 1,  2,  3,  4],
         [ 2,  3,  4,  5],
         [ 5,  6,  7,  8]]])

# Operations

In [32]:
# Get exp(x) elementwise
torch.exp(a)

tensor([[[1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
         [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
         [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05]],

        [[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02],
         [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03]]])

In [33]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([5,6,7,8],dtype=torch.float32)

x+y , x-y , x*y, x/y , x**y

(tensor([ 6.,  8., 10., 12.]),
 tensor([-4., -4., -4., -4.]),
 tensor([ 5., 12., 21., 32.]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]),
 tensor([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]))

In [34]:
# Concatenate two tensors
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]],dtype=torch.float32)
torch.cat((X,Y),dim=0) , torch.cat((X,Y),dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [35]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [36]:
X.sum()

tensor(66.)

# Broadcasting

In [37]:
# In different shapes, the operation is executed by broadcasting

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [38]:
# broadcast produces 3x2 tensor
a + b
"""
a is converted to 0 0
                  1 1
                  2 2

b is converted to 0 1
                  0 1
                  0 1

"""

'\na is converted to 0 0\n                  1 1\n                  2 2\n\nb is converted to 0 1\n                  0 1\n                  0 1\n\n'

In [39]:
x=torch.randn(60).reshape((5,4,3))
y=torch.ones((1,4,3))
x,y

(tensor([[[-1.4193,  1.4849, -1.2612],
          [-1.0456, -1.1110,  0.7762],
          [ 0.0216,  1.1671,  0.1594],
          [-1.0035, -1.5747,  0.6538]],
 
         [[-1.7221, -0.1295,  0.3512],
          [ 1.8500,  1.2711,  0.1198],
          [-0.2269,  0.2912,  1.0395],
          [-1.3004,  1.0406,  0.3464]],
 
         [[ 0.3934,  0.3459,  1.7538],
          [ 0.5210,  0.1407, -1.7868],
          [ 1.5942, -1.0033, -1.7751],
          [-0.0880,  0.3091, -1.6169]],
 
         [[-0.9552,  0.5475, -0.4859],
          [ 0.2219, -0.9319,  0.0622],
          [-0.5185, -0.0071,  0.4685],
          [ 1.5735, -2.3910, -0.3749]],
 
         [[-0.3890,  0.3311, -0.6632],
          [ 0.5651,  0.2530, -0.2100],
          [-0.3987,  0.6510, -1.0377],
          [ 0.6440, -0.0067, -0.5067]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [40]:
Y = torch.zeros((3,4))
X = torch.ones((3,4))

print(id(X))
print(id(Y))

Y = Y + X
id(Y)
#The id will change,that means python reallocated new object

138204844961168
138204860063936


138204844857744

In [41]:
Y = torch.ones((3,4))
X = torch.ones((3,4))
print(id(X))
print(id(Y))

Y[:] = X+ Y
id(Y)
#Id wont change, so more effective usage of the memory

138204844961648
138204844471248


138204844471248

# Data Preprocessing

In [42]:
import os


os.makedirs(os.path.join("..","data"),exist_ok = True)
data_path = os.path.join("..","data","house_tiny.csv")

with open(data_path,'w') as f:
  f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')


In [48]:
import pandas as pd

data = pd.read_csv("../data/house_tiny.csv")
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [49]:
inputs,targets = data.iloc[:,:2],data.iloc[:,2]
inputs = pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       NaN               0             1
1       2.0               0             1
2       4.0               1             0
3       NaN               0             1

In [53]:
#To impute nan in non-categorical variables is to take mean of the column
inputs = inputs.fillna(inputs.mean())
inputs

NumRooms  RoofType_Slate  RoofType_nan
0       3.0               0             1
1       2.0               0             1
2       4.0               1             0
3       3.0               0             1

In [55]:
#To load to torch tensor
X= torch.tensor(inputs.to_numpy(dtype=float))
y= torch.tensor(targets.to_numpy(dtype=float))
X,y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))