<a href="https://colab.research.google.com/github/demirbey05/pytorch-cookbook/blob/main/Torch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
# Create array of range 1 to 12
x = torch.arange(12, dtype = torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [ ]:
x.numel()

12

In [ ]:
x.shape

torch.Size([12])

In [ ]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X.shape

torch.Size([3, 4])

In [ ]:
Y = x.reshape(3,-1)
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
#Create 2 3x4 zeros Matrix meaning (2,3,4) shape

torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
#Create 2 3x4 ones Matrix meaning (2,3,4) shape
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [ ]:
#Create 2 3x4 random Matrix meaning (2,3,4) shape  Drawn from Gaussina mean 0 stdev 1

torch.randn((2,3,4))


tensor([[[-0.3345, -0.0773,  0.2781, -1.3221],
         [ 1.9029,  1.4754, -1.4848,  2.0995],
         [-1.2669, -1.4944,  0.6726,  0.9922]],

        [[ 0.7948, -1.1985, -0.1570, -0.7757],
         [ 1.8360, -0.0448,  0.9625,  1.0157],
         [-1.4525, -0.6477, -0.1668,  1.0591]]])

In [ ]:
#Create torch tensor manually with shape of 2,3,4
a = torch.tensor([[[2,1,3,4],[2,4,5,6],[6,5,3,2]],[[1,2,3,4],[2,3,4,5],[5,6,7,8]]])
a.shape

torch.Size([2, 3, 4])

# Indexing & Slicing

In [ ]:
# Indexing start with zero , X[start:stop] --> [start,stop) , -1 starts from the end
# When only one index is indicated in kth order tensor, the axis 0 will be selected
a[-1] # returns last matrix
a[0:2] # returns all
a[0:-1] # returns first matrix

tensor([[[2, 1, 3, 4],
         [2, 4, 5, 6],
         [6, 5, 3, 2]]])

In [ ]:
# We can index in more detail by indicating more index
a[0,0,0] = 3 # first matrix, first row , first column(axis 0,1,2)
a

tensor([[[3, 1, 3, 4],
         [2, 4, 5, 6],
         [6, 5, 3, 2]],

        [[1, 2, 3, 4],
         [2, 3, 4, 5],
         [5, 6, 7, 8]]])

In [ ]:
# To assign multiple elements
a[:1,:] = 12 ## assign first matrix's elems to 12
a

tensor([[[12, 12, 12, 12],
         [12, 12, 12, 12],
         [12, 12, 12, 12]],

        [[ 1,  2,  3,  4],
         [ 2,  3,  4,  5],
         [ 5,  6,  7,  8]]])

# Operations

In [ ]:
# Get exp(x) elementwise
torch.exp(a)

tensor([[[1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
         [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05],
         [1.6275e+05, 1.6275e+05, 1.6275e+05, 1.6275e+05]],

        [[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
         [7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02],
         [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03]]])

In [ ]:
x = torch.tensor([1,2,3,4],dtype=torch.float32)
y = torch.tensor([5,6,7,8],dtype=torch.float32)

x+y , x-y , x*y, x/y , x**y

(tensor([ 6.,  8., 10., 12.]),
 tensor([-4., -4., -4., -4.]),
 tensor([ 5., 12., 21., 32.]),
 tensor([0.2000, 0.3333, 0.4286, 0.5000]),
 tensor([1.0000e+00, 6.4000e+01, 2.1870e+03, 6.5536e+04]))

In [ ]:
# Concatenate two tensors
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]],dtype=torch.float32)
torch.cat((X,Y),dim=0) , torch.cat((X,Y),dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [ ]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [ ]:
X.sum()

tensor(66.)

# Broadcasting

In [ ]:
# In different shapes, the operation is executed by broadcasting

a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))

a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
# broadcast produces 3x2 tensor
a + b
"""
a is converted to 0 0
                  1 1
                  2 2

b is converted to 0 1
                  0 1
                  0 1

"""

In [ ]:
x=torch.randn(60).reshape((5,4,3))
y=torch.ones((1,4,3))
x,y

(tensor([[[ 0.3894, -0.4649, -0.5856],
          [-0.0935,  0.6471, -0.1045],
          [-0.8069,  1.3140, -0.3212],
          [-0.4951,  0.4591,  0.9493]],
 
         [[-0.2336, -1.6698, -2.2125],
          [-0.5491, -0.2202, -1.7277],
          [ 0.6667, -0.7512, -0.3466],
          [-0.0817, -0.7931, -1.0728]],
 
         [[ 0.9861, -0.7246, -1.4052],
          [ 1.0300, -1.2898,  1.7754],
          [ 1.3292,  0.3951,  0.6711],
          [-1.2173, -1.4115, -0.5370]],
 
         [[ 0.6001, -0.3692,  2.0187],
          [ 0.4794, -0.1606, -0.3507],
          [ 0.3845, -0.0318, -1.4918],
          [ 0.1252,  0.5901, -0.1798]],
 
         [[ 1.2700, -1.1363,  0.4303],
          [ 0.1025,  2.4732,  0.2701],
          [-0.0593, -0.0914, -1.5599],
          [-0.3936,  0.7621,  0.1479]]]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))